[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend/url-service && ./mvnw spring-boot:run"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
# These will be set in Railway dashboard
SPRING_PROFILES_ACTIVE = "production"