services:
  - type: web
    name: pebly-backend
    env: java
    buildCommand: cd url-service && mvn clean package -DskipTests
    startCommand: cd url-service && java -jar target/url-service-1.0.0.jar
    plan: starter
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        value: mongodb+srv://lahorivenkatesh709:p0SkcBwHo67ghvMW@cluster0.y8ucl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGODB_DATABASE
        value: pebly-database
      - key: FRONTEND_URL
        value: https://pebly.vercel.app
      - key: SHORT_URL_DOMAIN
        value: https://pebly.vercel.app
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        value: rzp_live_RWtmHyTZfva7rb
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: CACHE_TYPE
        value: simple