server:
  port: ${PORT:8080}

spring:
  application:
    name: url-service
  
  # CORS Configuration for Vercel frontend
  web:
    cors:
      allowed-origins: 
        - ${FRONTEND_URL:http://localhost:3000}
        - "https://*.vercel.app"
        - "https://your-domain.com"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/urlshortener}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  cache:
    type: simple

# Google OAuth Configuration
google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: ${GOOGLE_REDIRECT_URI:https://your-vercel-app.vercel.app/auth/callback}

logging:
  level:
    com.urlshortener: INFO
    org.springframework.security: DEBUG

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized