server:
  port: ${PORT:8080}

spring:
  application:
    name: pebly-backend
  
  # MongoDB Configuration - Disabled for simple mode
  data:
    mongodb:
      uri: # Disabled
  
  # Disable Redis for now to avoid connection issues
  cache:
    type: simple
  
  # Security - disable for now
  security:
    enabled: false
    
  # CORS
  web:
    cors:
      allowed-origins: 
        - ${FRONTEND_URL:http://localhost:3000}
        - "https://pebly.vercel.app"
        - "https://*.vercel.app"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

# Disable auto-configurations for simple mode
spring.autoconfigure.exclude: 
  - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  - org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration
  - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
  - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  - org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration

logging:
  level:
    com.urlshortener: DEBUG
    org.springframework: INFO
    org.mongodb: INFO