server:
  port: ${PORT:8080}

spring:
  application:
    name: pebly-url-service

  # MongoDB Configuration for Production
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://lahorivenkatesh709:p0SkcBwHo67ghvMW@cluster0.y8ucl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      database: ${MONGODB_DATABASE:pebly-database}
      auto-index-creation: false

  # CORS Configuration for Production
  web:
    cors:
      allowed-origins:
        - ${FRONTEND_URL:https://pebly.vercel.app}
        - "https://pebly.vercel.app"
        - "https://*.vercel.app"
        - "https://urlshortner-mrrl.onrender.com"
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
      allowed-headers:
        - "*"
      allow-credentials: true

  cache:
    type: ${CACHE_TYPE:simple}

# Application Configuration
app:
  frontend:
    url: ${FRONTEND_URL:https://pebly.vercel.app}
  shorturl:
    domain: ${SHORT_URL_DOMAIN:https://pebly.vercel.app}

# Logging Configuration for Production
logging:
  level:
    com.urlshortener: INFO
    org.springframework.security: WARN
    org.springframework.data.mongodb: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator configuration for Production
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: never
