server:
  port: ${PORT:8080}

spring:
  application:
    name: pebly-url-service

  # No MongoDB configuration for simple profile
  cache:
    type: simple

# Application Configuration
app:
  frontend:
    url: ${FRONTEND_URL:https://pebly.vercel.app}
  shorturl:
    domain: ${SHORT_URL_DOMAIN:https://pebly.vercel.app}

# Logging Configuration
logging:
  level:
    com.urlshortener: INFO
    org.springframework.security: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: never