server:
  port: ${PORT:8080}

spring:
  application:
    name: pebly-url-service

  # MongoDB Configuration (fallback)
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://lahorivenkatesh709:p0SkcBwHo67ghvMW@cluster0.y8ucl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      database: ${MONGODB_DATABASE:pebly-database}
      auto-index-creation: false
      
  cache:
    type: simple

# Application Configuration
app:
  frontend:
    url: ${FRONTEND_URL:https://pebly.vercel.app}
  shorturl:
    domain: ${SHORT_URL_DOMAIN:https://pebly.vercel.app}

# Logging Configuration
logging:
  level:
    com.urlshortener: INFO
    org.springframework.security: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: never